// Code generated by reset generator; DO NOT EDIT.
// go run ./cmd/reset

package storage

// Reset resets the DBStorage struct to its zero state.
func (s *DBStorage) Reset() {
	if s == nil {
		return
	}

	if s.conn != nil {
		if resetter, ok := interface{}(s.conn).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			// TODO: manually reset pointer field conn
		}
	}
	if s.cache != nil {
		if resetter, ok := interface{}(s.cache).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			// TODO: manually reset pointer field cache
		}
	}
	// Reset field mu of external type sync.RWMutex
	if resetter, ok := interface{}(&s.mu).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		// TODO: manually reset external field mu
	}
}

// Reset resets the FileStorage struct to its zero state.
func (s *FileStorage) Reset() {
	if s == nil {
		return
	}

	// Reset embedded field of type embedded
	if resetter, ok := interface{}(s).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	s.filePath = ""
	// Reset field mu of external type sync.Mutex
	if resetter, ok := interface{}(&s.mu).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		// TODO: manually reset external field mu
	}
}

// Reset resets the MemStorage struct to its zero state.
func (s *MemStorage) Reset() {
	if s == nil {
		return
	}

	clear(s.gauge)
	clear(s.counter)
	// Reset field mu of external type sync.RWMutex
	if resetter, ok := interface{}(&s.mu).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		// TODO: manually reset external field mu
	}
}
