// Code generated by reset generator; DO NOT EDIT.
// go run ./cmd/reset

package main

// Reset resets the Metrics struct to its zero state.
func (s *Metrics) Reset() {
	if s == nil {
		return
	}

	s.ID = ""
	s.MType = ""
	if s.Delta != nil {
		*s.Delta = 0
	}
	if s.Value != nil {
		*s.Value = 0
	}
}

// Reset resets the MetricQueue struct to its zero state.
func (s *MetricQueue) Reset() {
	if s == nil {
		return
	}

	// TODO: reset field queue of unknown type
	// Reset field pool of external type sync.Pool
	if resetter, ok := interface{}(&s.pool).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		// TODO: manually reset external field pool
	}
}

// Reset resets the httpError struct to its zero state.
func (s *httpError) Reset() {
	if s == nil {
		return
	}

	s.statusCode = 0
	s.msg = ""
}

// Reset resets the WorkerPool struct to its zero state.
func (s *WorkerPool) Reset() {
	if s == nil {
		return
	}

	s.workers = 0
	if s.queue != nil {
		if resetter, ok := interface{}(s.queue).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			// TODO: manually reset pointer field queue
		}
	}
	if s.client != nil {
		if resetter, ok := interface{}(s.client).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			// TODO: manually reset pointer field client
		}
	}
	s.serverAddr = ""
	// Reset field wg of external type sync.WaitGroup
	if resetter, ok := interface{}(&s.wg).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		// TODO: manually reset external field wg
	}
	// Reset field ctx of external type context.Context
	if resetter, ok := interface{}(&s.ctx).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		// TODO: manually reset external field ctx
	}
	// Reset field cancel of external type context.CancelFunc
	if resetter, ok := interface{}(&s.cancel).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		// TODO: manually reset external field cancel
	}
}
