// Code generated by reset generator; DO NOT EDIT.
// go run ./cmd/reset

package main

// Reset resets the AuditEvent struct to its zero state.
func (s *AuditEvent) Reset() {
	if s == nil {
		return
	}

	s.Timestamp = 0
	s.Metrics = s.Metrics[:0]
	s.IPAddress = ""
}

// Reset resets the Publisher struct to its zero state.
func (s *Publisher) Reset() {
	if s == nil {
		return
	}

	s.observers = s.observers[:0]
	// Reset field mutex of external type sync.RWMutex
	if resetter, ok := interface{}(&s.mutex).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		// TODO: manually reset external field mutex
	}
}

// Reset resets the FileWriterObserver struct to its zero state.
func (s *FileWriterObserver) Reset() {
	if s == nil {
		return
	}

	s.filePath = ""
	// Reset field mutex of external type sync.Mutex
	if resetter, ok := interface{}(&s.mutex).(interface{ Reset() }); ok {
		resetter.Reset()
	} else {
		// TODO: manually reset external field mutex
	}
}

// Reset resets the HTTPSenderObserver struct to its zero state.
func (s *HTTPSenderObserver) Reset() {
	if s == nil {
		return
	}

	s.url = ""
	if s.client != nil {
		if resetter, ok := interface{}(s.client).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			// TODO: manually reset pointer field client
		}
	}
}

// Reset resets the responseData struct to its zero state.
func (s *responseData) Reset() {
	if s == nil {
		return
	}

	s.status = 0
	s.size = 0
}

// Reset resets the loggingResponseWriter struct to its zero state.
func (s *loggingResponseWriter) Reset() {
	if s == nil {
		return
	}

	// Reset embedded field of type http.ResponseWriter
	if resetter, ok := interface{}(s).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if s.responseData != nil {
		if resetter, ok := interface{}(s.responseData).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			// TODO: manually reset pointer field responseData
		}
	}
}

// Reset resets the conditionalGzipResponseWriter struct to its zero state.
func (s *conditionalGzipResponseWriter) Reset() {
	if s == nil {
		return
	}

	// Reset embedded field of type http.ResponseWriter
	if resetter, ok := interface{}(s).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if s.gz != nil {
		if resetter, ok := interface{}(s.gz).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			// TODO: manually reset pointer field gz
		}
	}
	s.supportsGzip = false
	s.wroteHeader = false
}
